# Default values for person.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#kubectl create secret docker-registry docker --docker-server=https://index.docker.io/v1 --docker-username=zdhamasha --docker-password=lanax@Z454 --docker-email=zaidhamasha@gmail.com

image:
  repository: zdhamasha/person
  tag: "220919-6b5d8fa5"
  pullPolicy: Always

PSCI_BRANCH: ""
imagePullSecrets: ""
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: ""
  devopsDomain: "devops-dev-ing.progressoft.cloud"
certificate: 
    enabled: false


resources:
    limits:
      cpu: 1000m
      memory: 1048Mi
    requests:
      cpu: 200m
      memory: 512Mi
nodeSelector: {}

tolerations: []

affinity: {}
