server.port: 8080
server.address: 0.0.0.0
spring.application.name: person-service

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus