{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-ingress-cert-nginx
spec:
  commonName: "{{ .Values.ingress.hostname }}"
  dnsNames:
  - "{{ .Values.ingress.hostname }}"
  issuerRef:
    # group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-http-issuer-nginx
  secretName: "{{ .Release.Name }}-ingress-cert"
  # usages:
  # - digital signature
  # - key encipherment
  renewBefore: 360h0m0s
  subject:
    organizations:
    - progressoft
  duration: 2160h0m0s
{{- end }}
