{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations: 
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
  - hosts:
    {{- if .Values.ingress.hostname }}
      - {{ .Values.ingress.hostname }}
    {{- else}}
      - {{ .Release.Name }}-{{ .Chart.Name }}.{{ .Values.ingress.devopsDomain }}
    {{- end }}
    {{- if .Values.certificate.enabled }}
    secretName: "{{ .Release.Name }}-ingress-cert"
    {{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
  {{- else}}
  - host: {{ .Release.Name }}-{{ .Chart.Name }}.{{ .Values.ingress.devopsDomain }}
  {{- end }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "person.fullname" . }}
            port:
              number: 80

{{- end }}
