name: build
on:
  push:
    branches: [ "*", "!master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          export commitsha=$(/bin/bash scripts/commit.sh )
          mvn clean install
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: zdperson
          heroku_email: zaidhamasha@gmail.com
          usedocker: true