# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "*", "!master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: office
    steps:
      - uses: actions/checkout@v2
      - name: build-mvn
        run: |
          export commitsha=$(/bin/bash scripts/commit.sh )
          mvn clean install
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: zdperson
          heroku_email: zaidhamasha@gmail.com
          usedocker: true
      # - name: build-docker
      #   run: |
      #     export commitsha=$(/bin/bash scripts/commit.sh )
      #     docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }}
      #     docker build -t ${{ secrets.CI_REGISTRY_USER }}/${{ secrets.CI_PROJECT_NAME }}:$commitsha .
      #     docker push ${{ secrets.CI_REGISTRY_USER }}/${{ secrets.CI_PROJECT_NAME }}:$commitsha